[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "http://localhost:3000"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Credentials = "true"